### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by jessicaboggia** [Rainbow-Dreamer/SfPlayer#1]
I ran the .exe through Virus Total and it is showing up as positive for the Trojan.Generic.horqm trojan. 

Posting to make others aware and to make the authors aware in case this is a false positive they can fix.

Thanks.

**Comment by Rainbow-Dreamer** [comment]
Hi, thanks for the feedback, it seems that sometimes the exe files compiled by pyinstaller could be labeled as trojan in some antivirus software, this situation also happened to one of my project last year when I tried to run the compiled exe file on one of my workmates' pc, and you can also find many other cases on [stackoverflow](https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg). 
The only viable solution that I can find at this time is to either trust the exe file in your antivirus software, or compile the exe by yourself on your machine, you can refer to `Building from source` section in README, tries to compile a version for yourself.
